// Referência fixa para a IA: biblioteca de 100 modelos de gancho de abertura (docs/referencias/ganchos-de-abertura.txt,
// material "Swipe" de Rodrigo Vincenzi / STINT anotado só como estrutura; os exemplos do nicho original não foram copiados).
// Entra no contexto das tarefas marcadas com `ganchos: true` em TAREFAS (server/index.js): criativos e hooks. O modelo é a
// estrutura, não o texto final: a IA adapta ao produto, sem colchetes, sem repetir o modelo no lote e dizendo de qual veio
// (campo "modeloGancho"; o app confere em src/lib/ganchos.js). Os modelos com (*) prometem transformação: em cliente de
// saúde, suplemento ou emagrecimento não podem virar resultado no corpo (política do Meta e regras da Anvisa).
// Mudou a lista? Mude também o arquivo em docs/referencias/ e o cartão em src/modules/playbooks.js.

/** Lista como está no documento: "# GRUPO" e "N. modelo", com (*) nos que pedem cuidado em saúde. */
const LISTA = `# CURIOSIDADE E SEGREDO
1. Desafio você a pular esse vídeo antes de eu te contar sobre...
15. Aposto que você não fazia ideia disso sobre...
16. A verdade sobre [algo] que ninguém está te contando...
24. Eu ouvi boatos de que...
27. Quase ninguém sabe disso, mas...
29. O que ninguém jamais te falou sobre [algo]...
36. Você sabia que [algo] era capaz de fazer isso?
38. Todo mundo fala sobre isso, mas o segredo ninguém te conta...
41. A coisa mais surpreendente sobre [algo/marca]
44. Tentaram esconder isso de você, mas...
48. Por que ninguém está falando sobre [algo]?
51. O segredo para [resultado] que ninguém quer compartilhar...
54. Você está prestes a descobrir algo que vai mudar tudo...
55. Nunca te contaram isso, mas deveriam...
58. Isso é o que [alguém importante] não quer que você descubra...
69. O truque que poucos conhecem para [problema comum]
99. Você consegue adivinhar o segredo por trás de [algo]?
# QUEBRA DE CRENÇA E POLÊMICA
4. Isso vai gerar polêmica, mas preciso dizer...
7. Você consegue identificar o que é mentira sobre...?
11. [Alguma coisa] é uma farsa total!
19. Não vou te enganar, mas...
20. O que falaram sobre [coisa] era verdade mesmo
30. Isso virou completamente minha perspectiva sobre [algo]
40. Isso vai te fazer repensar sobre [algo]
45. Se você acha que [algo] não dá resultado, assiste isso...
68. Você está fazendo isso errado há muito tempo...
79. Se acha que sabe tudo sobre [algo], pensa de novo...
82. Isso não é o que você espera de [algo/marca]
86. Eu achei que era papo de autoajuda, mas...
91. Isso vai mudar completamente sua visão sobre [algo]
# DOR E PROBLEMA
10. Qual é a melhor [coisa] para [problema]?
47. Se você já travou em [algo], você precisa ver isso...
56. Se você está cansado de [algo], presta atenção nisso...
61. A única coisa que você precisa para resolver [problema]
71. Você está perdendo dinheiro se não está fazendo isso...
72. Encontrei a solução mais simples para [problema]
73. Se acha que já tentou tudo, assiste isso...
83. Finalmente! A solução para [problema frustrante]
89. Se pudesse resolver [problema] em 5 minutos, faria?
98. A resposta para [problema] está bem na sua frente...
# ALERTA E INTERRUPÇÃO
5. Assista ISSO antes de comprar qualquer...
17. Teste ISSO antes de ir para [algum lugar]
21. NÃO assine [X] sem assistir isso primeiro...
28. Antes de [X], faça [Y]
33. Para de [algo] até você ver isso...
60. Para tudo e presta atenção nisso!
76. Não ignore isso se você quer [resultado]
90. As 3 coisas que você precisa saber antes de [algo]
94. Esse é o sinal que você estava esperando para... [algo]
# EXPERIÊNCIA PESSOAL E TESTE (bom para UGC e Owner)
2. Quando a pessoa que eu admirava disse que gostava de [algo], eu vim mostrar isso aqui...
3. O que eu esperava vs. O que realmente recebi
6. Eu escondo ISSO quando estou em...
8. Espera aí... um [algo] que na verdade funciona?
9. Minha [coisa] favorita para [algo]
12. Acho engraçado que todo mundo acha que eu investi muito em [algo]
14. Como eu fui de [antes] para [depois] (*)
18. Um dia eu descobri algo que me transformou completamente como [alguém]
31. Você não vai acreditar no que aconteceu quando eu tentei [algo]
34. Disseram que não ia dar certo, mas...
37. Eu testei [algo] durante 30 dias e olha o que aconteceu... (*)
39. Isso eu não esperava de [algo/marca]
42. Como eu resolvi [um problema] em 5 minutos
43. O único motivo pelo qual eu ainda faço [algo]
46. Testei todas as alternativas e essa foi a melhor para [algo]
49. Isso foi o que aconteceu quando eu troquei [X] por [Y]
52. Eu fiz [algo] de um jeito errado por anos... até descobrir isso!
53. Por que eu nunca mais vou voltar para [algo antigo]
62. Como eu fiz [algo incrível] sem investir uma fortuna...
63. Desculpa, não consigo falar agora. Estou [fazendo algo interessante]
65. Se eu soubesse disso antes, teria economizado anos...
66. Tentaram me avisar, mas eu não escutei...
70. Se eu pudesse voltar no tempo, faria diferente...
74. Isso fez uma diferença enorme na minha vida! (*)
77. As pessoas sempre me perguntam como eu faço isso...
81. Eu fiz [algo simples] e mudou tudo...
84. Eu não acreditei até experimentar... (*)
85. Pode parecer estranho, mas funciona de verdade!
92. Eu apostei tudo e olha o que aconteceu...
93. Nunca mais vou voltar para [algo antigo]
96. Isso foi o que aconteceu quando eu resolvi mudar...
97. Nunca imaginei que [algo] fosse funcionar, mas...
100. Eu testei [algo] para ver se era verdade e...
# PROMESSA E RESULTADO (cuidado em clientes de saúde)
13. Me dá 15 segundos para mudar sua visão sobre [algo]
22. Essa é a fórmula perfeita para...
35. Isso vai salvar o seu [algo importante]
50. Eu te prometo que isso vai transformar a forma como você [algo]
59. Você sabia que é possível ter [resultado] com [algo]? (*)
64. Isso é o que realmente funciona para [resultado desejado] (*)
67. Aqui está o caminho mais rápido para [resultado] (*)
75. Você está pronto para transformar [problema] em [solução]?
78. Isso vai abrir seus olhos para [algo]
88. Você não precisa gastar muito para [resultado]
95. Você está a um passo de transformar [algo]
# COMPARAÇÃO, PÚBLICO E POSICIONAMENTO
23. Se você tem [X], você vai precisar de [Y]
25. Esse é o [X] que todos os [Y] estão usando...
26. Se está procurando por [X], você precisa conhecer [Y]...
32. As 3 coisas que eu queria ter sabido antes de [fazer algo]
57. É tipo [X], mas voltado para [Y]...
80. Se você é [X], aqui estão 5 razões para você precisar de [Y]
87. O que acontece quando você para de [hábito]?`;

/** [{ n, texto, grupo, cuidado }] — cuidado = marcado com (*) (transformação/resultado: bloqueado no corpo em saúde). */
export const GANCHOS = (() => {
  let grupo = '';
  return LISTA.split('\n').flatMap((l) => {
    if (l.startsWith('# ')) { grupo = l.slice(2).trim(); return []; }
    const m = /^(\d+)\. (.+?)( \(\*\))?$/.exec(l.trim());
    return m ? [{ n: Number(m[1]), texto: m[2].trim(), grupo, cuidado: Boolean(m[3]) }] : [];
  });
})();

export const GRUPOS_GANCHO = [...new Set(GANCHOS.map((g) => g.grupo))];

/** Modelo pelo número (1 a 100) ou null. */
export const ganchoPorNumero = (n) => GANCHOS.find((g) => g.n === Number(n)) || null;

export const REFERENCIA_GANCHOS = `REFERÊNCIA — Modelos de gancho de abertura (biblioteca numerada; uma referência entre outras: use quando o modelo couber no produto e no pedido, ignore quando nenhum couber; nunca passa por cima das REGRAS CRÍTICAS, da política de anúncios do Meta nem do perfil de marca). O formato de saída e os campos pedidos sempre valem sobre esta referência.
- Gancho = os 3 primeiros segundos do vídeo ou a primeira linha da imagem: para a rolagem e liga com o que vem depois.
- O modelo é a ESTRUTURA, não o texto: troque o que está entre colchetes (e "X"/"Y") pelo produto, problema ou resultado REAL do cliente, no tom do perfil de marca. O texto final nunca tem colchetes. Se não houver dado real para preencher o modelo, escolha outro.
- Números e prazos do modelo (30 dias, 5 minutos, 15 segundos, "3 coisas") só ficam se forem verdade para o produto; senão, tire o número ou troque de modelo. "Eu testei", "eu descobri" e afins só como roteiro de UGC/Owner, sem inventar resultado, número, depoimento nem antes e depois.
- "Segredo", "farsa", "esconderam de você": só quando há algo real para revelar; senão soa golpe.
- Num lote, cada variação usa um modelo DIFERENTE (nunca o mesmo número duas vezes), de preferência de grupos diferentes.
- Diga de qual modelo veio no campo pedido (o número); se o gancho não veio de nenhum modelo, devolva null. Não atribua a um modelo o que não segue a estrutura dele.
- (*) = modelo de transformação/resultado. Em produto de saúde, suplemento ou emagrecimento, o (*) NUNCA vira resultado no corpo (peso, kg, medidas, barriga, "meu corpo mudou", antes e depois, transformação física) nem autoimagem negativa: só pode ser usado se o que for citado for permitido (experiência de uso, rotina, praticidade, composição real), sem prometer efeito no corpo (energia, disposição, metabolismo, apetite); na dúvida, escolha outro modelo. Nesses clientes, modelo que fala da condição de quem assiste ("Se você está cansado de...", "sem energia", "seu corpo") também não serve. Os modelos do grupo PROMESSA E RESULTADO pedem o mesmo cuidado nesses clientes.

${LISTA.replace(/^# (.+)$/gm, '\n$1:').trim()}`;
